package jp.elfeuille.gradle.ex.core.mapper;

import java.util.List;
import jp.elfeuille.gradle.ex.core.entity.SchemaChangeTestTable;
import jp.elfeuille.gradle.ex.core.entity.SchemaChangeTestTableExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SchemaChangeTestTableMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@SelectProvider(type = SchemaChangeTestTableSqlProvider.class, method = "countByExample")
	int countByExample(SchemaChangeTestTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@DeleteProvider(type = SchemaChangeTestTableSqlProvider.class, method = "deleteByExample")
	int deleteByExample(SchemaChangeTestTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@Delete({"delete from schema_change_test_table", "where id = #{id,jdbcType=INTEGER}"})
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@Insert({"insert into schema_change_test_table (id, value)", "values (#{id,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR})"})
	int insert(SchemaChangeTestTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@InsertProvider(type = SchemaChangeTestTableSqlProvider.class, method = "insertSelective")
	int insertSelective(SchemaChangeTestTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@SelectProvider(type = SchemaChangeTestTableSqlProvider.class, method = "selectByExample")
	@Results({@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "value", property = "value", jdbcType = JdbcType.VARCHAR)})
	List<SchemaChangeTestTable> selectByExample(SchemaChangeTestTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@Select({"select", "id, value", "from schema_change_test_table", "where id = #{id,jdbcType=INTEGER}"})
	@Results({@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "value", property = "value", jdbcType = JdbcType.VARCHAR)})
	SchemaChangeTestTable selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@UpdateProvider(type = SchemaChangeTestTableSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") SchemaChangeTestTable record, @Param("example") SchemaChangeTestTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@UpdateProvider(type = SchemaChangeTestTableSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") SchemaChangeTestTable record, @Param("example") SchemaChangeTestTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@UpdateProvider(type = SchemaChangeTestTableSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(SchemaChangeTestTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	@Update({"update schema_change_test_table", "set value = #{value,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}"})
	int updateByPrimaryKey(SchemaChangeTestTable record);
}