package jp.elfeuille.gradle.ex.core.entity;

import java.io.Serializable;

public class SchemaChangeTestTable implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schema_change_test_table.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schema_change_test_table.value
	 * @mbggenerated
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schema_change_test_table
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schema_change_test_table.id
	 * @return  the value of schema_change_test_table.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schema_change_test_table.id
	 * @param id  the value for schema_change_test_table.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schema_change_test_table.value
	 * @return  the value of schema_change_test_table.value
	 * @mbggenerated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schema_change_test_table.value
	 * @param value  the value for schema_change_test_table.value
	 * @mbggenerated
	 */
	public void setValue(String value) {
		this.value = value;
	}
}